[package]
name = "nickel-app"
version = "0.1.0"
edition = "2021"
authors = ["togido <togido@proton.me>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nickel = "*"
chrono = "0.4"